import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {validatePlan,tableVariant,tableGap,planSvg} from '../src/plan.mjs';
import {extractPlan,createServer} from '../server.mjs';
const sample=JSON.parse(await readFile(new URL('../public/sample/apartment.json',import.meta.url)));
test('sample geometry and both furniture decisions are valid and dimensioned',()=>{const p=validatePlan(sample);assert.equal(tableGap(p),.95);assert.equal(tableGap(tableVariant(p,true)),.65);assert.equal(p.furniture.find(f=>f.id==='dining').w,1.6);});
test('reject malformed and excessive geometry before rendering',()=>{for(const mutate of [p=>p.width=Infinity,p=>p.walls[0].x2=50,p=>p.furniture[0].x=-1,p=>p.rooms[0].w=500,p=>p.furniture[1].id=p.furniture[0].id,p=>p.walls=[]]){const p=structuredClone(sample);mutate(p);assert.throws(()=>validatePlan(p));}});
test('plan labels are escaped and unknown fields stripped',()=>{const p={...structuredClone(sample),name:'<script>alert(1)</script>',execute:'evil()'};assert(!('execute' in validatePlan(p)));assert(!planSvg(p).includes('<script>'));});
const image='data:image/png;base64,aGVsbG8=';
test('live extraction contract sends image and strict schema, never embeds a client credential',async()=>{let sent;const p=await extractPlan({image,width:9,depth:8},{OPENAI_API_KEY:'fixture-key'},async(url,opts)=>{sent={url,opts,body:JSON.parse(opts.body)};return {ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(sample)}]}]})};});assert.equal(sent.url,'https://api.openai.com/v1/responses');assert.equal(sent.body.store,false);assert.equal(sent.body.text.format.strict,true);assert.equal(sent.body.input[0].content[1].image_url,image);assert.equal(p.width,9);assert(!JSON.stringify(p).includes('fixture-key'));});
test('missing credentials, invalid images, provider failures and refusal handled explicitly',async()=>{await assert.rejects(()=>extractPlan({},{},()=>{}),/server/);await assert.rejects(()=>extractPlan({image:'https://evil.test',width:9,depth:8},{OPENAI_API_KEY:'fixture'},()=>{}),/PNG/);await assert.rejects(()=>extractPlan({image,width:9,depth:8},{OPENAI_API_KEY:'fixture'},async()=>({ok:false})),/provider/);await assert.rejects(()=>extractPlan({image,width:9,depth:8},{OPENAI_API_KEY:'fixture'},async()=>({ok:true,json:async()=>({output:[{content:[{type:'refusal'}]}]})})),/could not extract/);});
test('server protects live extraction and exposes only configuration booleans',async t=>{assert.throws(()=>createServer({HOST:'0.0.0.0'}),/32/);const app=createServer({HOST:'127.0.0.1',OPENAI_API_KEY:'fixture-secret',APP_ACCESS_TOKEN:'test-access'});await new Promise(r=>app.listen(0,'127.0.0.1',r));t.after(()=>app.close());const url=`http://127.0.0.1:${app.address().port}`;const r=await fetch(url+'/api/config');assert.deepEqual(await r.json(),{aiEnabled:true,accessRequired:true});assert.equal((await fetch(url+'/api/extract',{method:'POST'})).status,401);assert.equal((await fetch(url+'/api/extract',{method:'POST',headers:{Origin:'https://evil.test'}})).status,403);assert.equal((await fetch(url+'/.env')).status,403);assert.equal(r.headers.get('x-content-type-options'),'nosniff');});

test('reject a provider result with a different scale',async()=>{await assert.rejects(()=>extractPlan({image,width:10,depth:8},{OPENAI_API_KEY:'fixture'},async()=>({ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify(sample)}]}]})})),/geometry needs correction/);});
